### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by Muhammadquran** [xpol11/Gorilla-tag-kick#1]

**Comment by xpol11** [comment]
This isnt a virus lol. It inject codes into gorilla tag plus its obfuscated. So they may flag some antiviruses

**Comment by Muhammadquran** [comment]
you made it say that it is outdated, its either a virus, or a troll. i used my virtual machine. so if it is a virus, im safe. also its pretty sus that it is a python program.

**Comment by xpol11** [comment]
It says it outdated? Does it say anything else?
